language: java
jdk:
- oraclejdk8
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy >/dev/null
    2>&1
  skip_cleanup: true
  on:
    repo: PeterWarren/portal-core
    branch: master
env:
  global:
  - secure: K1MSp3YoWlBJc8t0PXmtFWxe9GKePB3GQortswV9HM4u8oKiwVMAw/o12+Wev0JtMW7FhDCqRv273qiTI/70TkhQ+DFMfMg2QhOtB7NkevLFn9ad0MkM+fZgFMm5HKfjhs2uXdHxa5+24zL0kflptPYHdv784ocYEaDzuKGN0wEc63un3PScHp2fJct9sOYVsYmFK/l5Cf64f+63anRFy+C1r+leA9iDT0x66tDVcqOdhZJtqLpZcAuSdZHCQUL0/AfolQVBDEt3v+2dB4wQn/v6vv4/d5xma9JIDYej/XDxLzffbfhN+zKer5MdvTfY6Jm+iYBWTNFLltWq7tJXIZ9FtHTIll9C+uuz/eF5aWcI5sn4vzNey0vnSgvCS4iaxRVbMu0hF0BQ1FZFvw+Be17O73egO4sSgalV/yTIoywWXscW8qb1OZxe3BrWkCLiNjZU6XXoBuCnkxItVLGLm0imYMfjZ9QYpV8NixX1LJCD9xQ3Wv4hpz6icfZhhDw+6L6E03mgGa5uuhnhcGwA1ccfUd65ZNns66TO2XLUTcgv0vsTzl1Ve1D3ztz1Ataj91FeIvG4/HbNaRa3FMw5NOy+MXxg+jQ/zxiQHucdg2p3NLip7qtguIFhhEiLzYyPcPNMln/OtUs7J6uAu9/OeV/1kn6zCNRQzo19yF6rZNw=
  - secure: k/04rP5td6Q0xNNm9JG+og23Ym9p0fzC8ZVC5lJgQ+DSwH0dL9OvhBP2DD9/f46EAEoQoNspqXm9Ph/yAtfXxVVYr0AxjyT4KB2GGlev46TA7aJQYve+9liyPoMFvKl4TlQmshunwPX95CjNiqLCSpxd060IelXHm1r1pYrBDP3kL4iOfPkAJ9aqC+qy/BBJtnZeLms2CX9n4sHLfRG50g6sDoBcQvYQqUJuxMT6wdUMBozUqNjYYROSEe3C7OT31jDhzARbuTW4J6aLHO/Oxr5T3DdVbDWXokGqo0ZyVDJMb7WSYWZ2aW1Dj7eTt3uF0OWimGHRugGwWqKCTxz57d53FLJGbkqVITvrNVRWIroJc4Z42+OnAoVhRMhLKreLQAjc9Iz2Ph37hb1lQanD/6iztZUScjz7TIeP3mxxlKhNaJaliyvvqJ4th9xui2ysng48uYF4Eu9B/1Vvu3IOyzeE30qFRFcssAyYCVh1WC8MYTf/2PLIxDALFkPpZbOrM+LzVvi8R+OGnSPvldb7qPpirMQB+MIrvxI27BWkoY3B9M7nWOD4qC0kqfi1MNwXLJnXkHKsSc+s2Ch4y97UCu0r3T3ryylDFRI1h1Hv+EAS+oVd5mu5uDYjqFcYYMdCNKRILJ+VcMGNA7AMScpfCjtrwydKGqRJQtK+HRZWxiA=
