language: java
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings travis/settings.xml || mvn clean verify --settings travis/settings.xml"
cache:
  directories:
    - $HOME/.m2
branches:
        only:              
                - master-ga2
jdk:
  - oraclejdk8
env:
        global:
                - secure: "MmAJ3GI23mR8ynBICBC/T3h/80m3gN2Twjvu/ODU9aYtfS0tgOBpvY6I4j7Fx/T+wXyJItDR5dGV0aDsnalJe9k3Ye19FHi8FSqojGAKB2Sk+L19kT6MxOMEpvTDbQRq1s1WZ6GiZrhWJvUgsigD2IEPaW2sIu6ZiPnUxTinLpw="
                - secure: "rVmDdrGb3RfvIcW6XIENBG0cd1biCGsoyT8HhUykZxMVMUeQMntBeespjOhrHGWbtKTyo0DIvPRjLbaDCBkWi2qs5YE9TE7AOhDALRcCBnHC5iPjWdBTinNJPjA3yHccWXpx6ti+WIOQwMWHip59qZ4r9VmfJNA5BdbJcQVlIwo="
notifications:
        slack:
                rooms:
                        - secure: "ubhiYEPFFJ6MivqNIPzRRgERU2Io+JMcmlBpFqD2Ha/aJh4kIc2ag3X6XnPg3Xm1vIr7jR4A8m9z+Fgd3mUXrZNwQbQA8jU36zzUxyxxU0wx5ingBUB8d6A+029KFc74DmgNPLcBNWgaAbZJWHLOAIAx1VPIEGABe1iE7fkCUAA="
