# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- Release-*

pool:
  vmImage: ubuntu-latest

container: maven:3.8.4-openjdk-17-slim

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'path'
    jdkDirectory: '/usr/local/openjdk-17'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'aus-mvn'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    publishJUnitResults: false
    javaHomeOption: 'path'
    jdkDirectory: '/usr/local/openjdk-17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))