#This workflow will build a Java project with Maven - to generate coverage in the file jacaco.csv. 
# This file is then parsed to generate a coverage percentage.
# readme.MD is then updated with this value to make a coverage badge.

name: coverage
      
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "master" ]

# runs tests and generate Jacoco report
# 
jobs:
  # This workflow contains a single job called "coverage"
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Show GitHub context   
        env:
           GITHUB_CONTEXT: ${{ toJson(github) }}   
        run: |
           #echo "$GITHUB_CONTEXT"
           echo {{ github.actor }}
           echo {{ github.author.email }}
      - run: echo "Start step"
      - uses: actions/checkout@v2
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - run: echo "maven step"
      - name: run tests with Maven
        run: |
          mvn verify --file pom.xml
      - name: Run coverage parse script
        run: |
         chmod +x scripts/coverage_percentage.sh
         percent=`scripts/coverage_percentage.sh`
         echo "percent="$percent
         echo $percent > .github/coverage/percentage.txt
         echo coverage = $percent
         cat /home/runner/work/portal-core/portal-core/target/site/jacoco/jacoco.csv > .github/coverage/jacoco.csv
        shell: bash

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2

      - name: Log coverage percentage
        run: |
           echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
           echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

        
      - run: echo "End step"
